// import { authOptions } from "@/auth";
import type { Metadata } from "next";
// import { getServerSession } from "next-auth/next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function HTMLLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
